build:
    nodes:
        analysis:
            tests:
                override:
                    - php-scrutinizer-run
    environment:
        variables:
            COMPOSER_MEMORY_LIMIT: -1

filter:
    excluded_paths: [spec/*, tests/*]

tools:
    external_code_coverage:
        timeout: 1200
